#                                         #
#               BattleDrones              #
#                   by                    #
#                MathiasMC                #
#  Any ideas for the plugin or need help? #
#           contact me on spigot          #
#                                         #

# Check for updates on startup?
update-check: true

# Drone health in gui
health:

  health:
    symbol: \u007c
    color: '&2'

  none:
    symbol: \u007c
    color: '&c'
  amount: 20

# Drone health placeholder
health-placeholder:

  health:
    symbol: \u007c
    color: '&2'

  none:
    symbol: \u007c
    color: '&c'
  amount: 20

# WorldGuard support (allow only attack in regions)
worldguard: []

# Vault (Use vault economy instead of build in coins system)
vault: false

# Drone count (How many drones can be active at the same time)
drone-amount: 10

# Save every x amount of minutes
save:
  use: true
  interval: 60

# Player death
player-death-commands:
  - 'battledrones message {player} &7[&dBattleDrones&7] &cYou had an active drone and it was removed, you died.'

# Custom heads for drones, gui - (base64 textures find one on minecraft-heads.com) (whitelist, cannot be removed) (Check if the head belongs somewhere before removing)
heads:
  player: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWU0NTAyOGI0ZTE2MDQ5MWEwYWU1OTRhNmNiNTVhYjcwNjlkMWZlNWM3OTc2ZGRhMzIyMDdhODlhMWNjMWUwMyJ9fX0=
  whitelist: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWU0NTAyOGI0ZTE2MDQ5MWEwYWU1OTRhNmNiNTVhYjcwNjlkMWZlNWM3OTc2ZGRhMzIyMDdhODlhMWNjMWUwMyJ9fX0=
  cow: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ2YzZlZGE5NDJmN2Y1ZjcxYzMxNjFjNzMwNmY0YWVkMzA3ZDgyODk1ZjlkMmIwN2FiNDUyNTcxOGVkYzUifX19
  laser-1: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzQxMjY1ZDU3ZDM3MDZjMGI0MjhmMWIyNDMwNDRkNTBkODQxNDkyNmFjYjM3NTJiOGNiOWY1Yjg1YmNkZDA5NiJ9fX0=
  laser-2: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliOTkyMzhkOWY4MTM0MDE1ZDc0MzQxYjE3MTE1YmUzMGYxMjVhMzdlYTQ5MDMyYjhjOWUzYjc2OWNmN2VlMSJ9fX0=
  laser-3: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZhN2QyMTk1ZmY3Njc0YmJiMTJlMmY3NTc4YTJhNjNjNTRhOTgwZTY0NzQ0NDUwYWM2NjU2ZTA1YTc5MDQ5OSJ9fX0=
  rocket-1: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDZkYjEzN2EzNTY3OWJlYWY3OTAwNzBkMGM5Yzk2YzkwNjc2MjYwZWJjMDBkZDJjNzAwNTYyYTA5OWRiMDdjMCJ9fX0=
  rocket-2: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODdlZTRlNDg5NWE5YzZlMjQzMzZlMjQ2NjVjNTYzODI3MmEzZmVlYWM5NTU4ODJmZjkyYWUzMjE1YWU3ZiJ9fX0=
  rocket-3: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzBlZTk2NjEyMzAwMWY3ZTc4ODllMDQ2YjM4ZTlkMjE2Yjg2YjQwZWFkMmIxNGYwNjQ5OTRkYzc4MzAwMGNmZiJ9fX0=
  rocket-head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWQ2NTVkNzk1MjNmOGM3MzQ1ZDQ1MGVkOWZhY2VhNzA4ZWRlZjJlNzA4N2UwYzQ2MzE3N2E3ODQ0ODBmNDkzZSJ9fX0=
  machine-gun-1: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2ZmNGI4ZThkZWFmYzYwYzMzMTlmNDQ5ZTU1ODFiMzNlZmMyYzFmYjZjYThiZGJlNGM3MjI3NjIxYjhiNyJ9fX0=
  machine-gun-2: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmIyYWJkNjY5MzlmNGNiNzI1N2E4OGNmNTJmYmM2ZmRjZWVjMTQzM2VjMmE2ZWYxNmQ2MmUzNGY2MjM4NzgxIn19fQ==
  shield-generator-1: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGI1N2E0YzY4ZDFkMmM1ZGU5NzhlYTZkZTRkYjkxZWYzODdjYTZjMzc5NjZiYjhlN2M4ODI2ZjkzN2U2YzMifX19
  shield-generator-2: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMGQ2MWFiMDEzNmM2OWQ3Y2FkZGQ1NjZkMmU5YmNiMzVmZGM1ZjllM2NhMzUxZTI3MzYyYWJmMTM3NGM0ZTU4In19fQ==
  shield-generator-3: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTE3NWJkZjQ3YWVhMWE0YmYxZDM0OWJlNmI3ZmE0YWIzN2Y0Nzk2NzJmNGM0M2FjYTU3NTExYjQyN2FiNCJ9fX0=
  shield-generator-4: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGZkMTJmOTlhNzJiYmJkMTliMzdlMWYzMjhkOWUwOTcxODA2NjE1OTM3NGI2YTE0MTRiODY5OGNlMzcwMzJkYiJ9fX0=
  healing-1: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTEzYmY3NWRmZmI4MTZiYWVhNmJjMmE3NTNlZDVlMTZiOTgzOTFmZGU1MzNiYWVhY2EzYjhiOWY0YWE3YjEifX19
  healing-2: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjZiN2UwYWM5YjExNzg5N2UyZTI5ZDllMTczNDg1MTNkNTU4YjZiMGNlZWRmZTA5ZjlhZDY3NDczZTg3Y2U4MyJ9fX0=
  healing-3: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTFjYTY1MjhkZWVlZDFjZWFiN2RlODU0ZWQ5NGVlMmMzZTdkODE5NWI0YWVlYmFiMTgyYmMwMDVkNjU3MDdlNiJ9fX0=

# Drone dead
dead:

  # Level to set the drone to when dead (0 = disable, the level must be found for the drone)
  set-level: 1

  # This value can only be 0-1 (0 the drone will be locked)
  unlocked: 0

  # Keep ammo on drone dead?
  ammo: false

  player:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYour drone was destroyed by the enemy.'

  wear:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYour drone was destroyed by wear and tear.'

low-ammo:

  # if player has 0% left warn the player!
  0:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou dont have any more ammo left.'

  # if player has 10% left warn the player!
  10:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on ammo only 10% left.'

  # if player has 50% left warn the player!
  50:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on ammo only 50% left.'