#                                         #
#               BattleDrones              #
#                   by                    #
#                MathiasMC                #
#  Any ideas for the plugin or need help? #
#           contact me on spigot          #
#                                         #

# Check for plugin updates on server startup?
update-check: true

# Disabled Drones List
# Drones listed here will be completely disabled.
# Corresponding files for these drones can be safely removed.
disable: []

# Stationary Mode Configuration
# When enabled, drones remain fixed at their spawn locations.
# Drones will not follow any targets or move from their initial position.
# Specify the list of drones that should operate in stationary mode below.
stationary-mode:
  - laser

# MySQL Database Configuration
mysql:
  use: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password

# Drone health display configuration (GUI)
health:

  health:
    symbol: \u007c          # Symbol used to represent health units
    color: '&2'             # Color code for health

  none:
    symbol: \u007c          # Symbol used to represent health units
    color: '&c'             # Color code for health

  amount: 20                # Total health units displayed

# Drone health placeholder (external plugin placeholder)
health-placeholder:

  health:
    symbol: \u007c          # Symbol used to represent health units
    color: '&2'             # Color code for health

  none:
    symbol: \u007c          # Symbol used to represent health units
    color: '&c'             # Color code for health

  amount: 20                # Total health units displayed

# Drone ammo display configuration (GUI)
ammo:

  ammo:
    symbol: \u007c          # Symbol used to represent health units
    color: '&2'             # Color code for health

  none:
    symbol: \u007c          # Symbol used to represent health units
    color: '&c'             # Color code for health

  amount: 20                # Total health units displayed

# Drone ammo placeholder (external plugin placeholder)
ammo-placeholder:

  ammo:
    symbol: \u007c          # Symbol used to represent health units
    color: '&2'             # Color code for health

  none:
    symbol: \u007c          # Symbol used to represent health units
    color: '&c'             # Color code for health

  amount: 20                # Total health units displayed

# Quick spawn/despawn drone by swapping items between main hand and off hand
swap:
  # Enable quick swap functionality (requires server restart to apply)
  use: true
  # Require Shift key during swap?
  shift: true

# Drone controller (you can get the controller by using /bd give controller <player> <range>)
controller:

  use: true

  NAME: '&dDrone controller'
  LORE:
    - '&f-----------------'
    - ''
    - '&7LMB to select target'
    - ''
    - '&7RMB to remove target'
    - ''
    - '&7Shift + RMB to switch mode'
    - ''
    - '&7Shift + LMB to follow target'
    - ''
    - '&7Range: &6{range}'
    - ''
    - '&7Only works if has active drone'
    - ''
    - '&f-----------------'
  MATERIAL: GOLDEN_AXE

  # Damage item 0 to disable
  damage:
    select: 2
    remove: 1
    follow: 5
    automatic: 1
    manual: 1

  # Exclude entity´s (Example silverfish) (entity´s in this list cannot be selected as target)
  exclude:
    - villager
    - vindicator
    - iron_golem
    - silverfish

  # Line of particles when selecting a target
  particle:
    use: true
    r: 255
    g: 255
    b: 255
    size: 1
    amount: 1
    space: 1.8

# Follow path
follow:

  close:
    # Range it will apply new speed (drone distance to target is lower than range)
    range: 5
    # Speed the drone will fly (0.value is recommend or it will be too fast)
    speed: 0.25

  middle:
    speed: 0.2

  far:
    # Range it will apply new speed (drone distance to target is higher than range)
    range: 6
    speed: 0.14

  # You can add as many as you want this is an big circle and small circle with locations around target
  # Example high point and low point in the y axis
  locations:
    1:
      # Distance is the amount of points in the circle (only integers)
      distance: 10
      # Radius and y-offset can be values of 0.0 example)
      radius: 4
      y-offset: 1.2
    2:
      # Distance is the amount of points in the circle (only integers)
      distance: 16
      # Radius and y-offset can be values of 0.0 example)
      radius: 8
      y-offset: 2.9
    3:
      # Distance is the amount of points in the circle (only integers)
      distance: 20
      # Radius and y-offset can be values of 0.0 example)
      radius: 12
      y-offset: 4.8

# Vault (Use vault economy instead of build in coins system)
vault: false

# Automatic disable toggles on world change
auto-disable:
  world_nether:
    commands:
      - 'battledrones message {player} &7[&dBattleDrones&7] &cDisabled your drone will not attack {types}'
    # PLAYERS, ANIMALS, MONSTERS
    list:
      - PLAYERS

# prune Interval (in minutes)
# Removed armor stands identified as drones.
# Note: Only removes stuck drones or projectiles, not active player-controlled drones.
prune: 20

# Update drone on upgrade
update-upgrade: true

# Update toggles on click
update-toggle: true

# Owner of drone can shift right click to open drone menu
drone-click: true

# Drone count (How many drones can be active at the same time)
drone-amount: 100

# Drone blacklist and whitelist
drone-worlds:
  blacklist: true
  whitelist:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cDrone {drone} is not allowed in the world {world}'
  list:
    world_nether:
      laser:
        - 'battledrones message {player} &7[&dBattleDrones&7] &cYou cannot use the laser drone in this world.'
      rocket:
        - 'battledrones message {player} &7[&dBattleDrones&7] &cYou cannot use the rocket drone in this world.'

# Player death (if section is removed the drone will not be removed) [] (to disable commands)
player-death-commands:
  - 'battledrones message {player} &7[&dBattleDrones&7] &cYou had an active drone and it was removed, you died.'

# Player change world (if section is removed the drone will not be removed) [] (to disable commands)
player-world-change-commands:
  - 'battledrones message {player} &7[&dBattleDrones&7] &cYou had an active drone and it was removed, you changed world.'

low-ammo:

  # if player has 0% left warn the player!
  0:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou dont have any more ammo left.'

  # if player has 10% left warn the player!
  10:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on ammo only 10% left.'

  # if player has 50% left warn the player!
  50:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on ammo only 50% left.'

low-health:

  # if player has 0% left warn the player!
  0:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou dont have any more health left.'

  # if player has 10% left warn the player!
  10:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on health only 10% left.'
    - 'battledrones actionbar {player} 1 &4Warning your drone is about to die. (10% health)'

  # if player has 20% left warn the player!
  20:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on health only 20% left.'
    - 'battledrones actionbar {player} 1 &4Warning your drone is about to die. (20% health)'

  # if player has 30% left warn the player!
  30:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on health only 30% left.'
    - 'battledrones actionbar {player} 1 &4Warning your drone is about to die. (30% health)'

  # if player has 60% left warn the player!
  60:
    - 'battledrones message {player} &7[&dBattleDrones&7] &cYou are low on health only 60% left.'
    - 'battledrones actionbar {player} 1 &4Warning your drone only has 60% health'