main: me.MathiasMC.BattleDrones.BattleDrones
version: ${project.version}
name: ${project.name}
author: MathiasMC
description: ${project.description}
api-version: 1.15
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard, Vault]
commands:
  battledrones:
    description: BattleDrones main command
    aliases: [bd]